language: node_js
dist: trusty
sudo: required
node_js: node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
cache: yarn
script:
  - yarn lint
  - yarn build:ngx-raptorize && yarn build
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   local-dir: dist/ngx-raptorize-demo
#   on:
#     branch: master

branches:
  only:
    - 'master'
