name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.15
      - name: Install dependencies
        run: yarn
      - name: Build lib
        run: yarn build:ngx-raptorize
      - name: Copy README.md & LICENSE in lib
        run: cp {README.md,LICENSE} dist/ngx-raptorize
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn semantic-release

      - name: Build app
        run: yarn build:ngx-raptorize && yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: dist/ngx-raptorize-demo
